source 'https://github.com/CocoaPods/Specs'
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

xcodeproj 'SeruTests'
workspace '../Seru'

pod 'Nimble', :git => 'https://github.com/Quick/Nimble', :branch => 'swift-1.1'
pod 'Seru', :path => '../'
