source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'Seru', :exclusive => true do
  pod "Seru", :path => "../"
end

target 'SeruTests', :exclusive => true do
  pod "Seru", :path => "../"
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-1.1'
end
