source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

pod 'Seru', :path => "../"
pod 'Sweet'

target 'SeruDemoTests' do

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'

end
