source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

pod "Seru", :path => "../"
pod "Sweet", :git => "https://github.com/kostiakoval/Sweet", :branch => 'swift_2.0'

target 'SeruDemoTests' do

  pod 'Quick', '~> 0.5.0'
  pod 'Nimble', '2.0.0-rc.2'

end
